[build]
  # Build from repo root (this folder) where Astro lives
  command = "npm ci && npm run build"
  # Publish the built static site
  publish = "dist"

[build.environment]
  # Ensure a modern Node for Astro 5
  NODE_VERSION = "22"

[functions]
  # Functions directory relative to this repo root
  directory = "netlify/functions"
